[tox]
envlist = flake8, black

[testenv:flake8]
skip_install = True
deps =
    flake8
commands =
    flake8

[testenv:format]
skip_install = True
deps =
    ruff
commands =
    ruff format {posargs:--check setup.py git_find_repos.py}
